package com.b1gbr0ther

object VoiceCommandAliases {
    val commandAliases = mapOf(
        "stop tracking" to listOf(
            "stop tracking",
            "end tracking",
            "finish tracking",
            "stop work",
            "end work",
            "finish work",
            "stop working",
            "end working",
            "i'm done",
            "finish task",
            "complete task",
            "done working",
            "that's all",
            "stop the task"
        ),
        "start break" to listOf(
            "log break",
            "begin break",
            "take break",
            "take a break",
            "start a break",
            "begin a break",
            "going on break",
            "need a break",
            "break time",
            "time for break",
            "pause work"
        ),
        "stop break" to listOf(
            "stop break",
            "end break",
            "finish break",
            "stop the break",
            "end the break",
            "finish the break",
            "break ended",
            "break finished",
            "break is over",
            "breaks over",
            "break over",
            "done with break",
            "finished break",
            "back to work",
            "resume work"
        ),
        "show export" to listOf(
            "show export",
            "export data",
            "open export",
            "show exports",
            "export page",
            "open exports",
            "view export",
            "view exports",
            "export my data"
        ),
        "show manual" to listOf(
            "show manual",
            "open manual",
            "show help",
            "open help",
            "help page",
            "manual page",
            "need help",
            "how to use",
            "instructions"
        ),
        "show timesheet" to listOf(
            "show timesheet",
            "open timesheet",
            "view timesheet",
            "show time sheet",
            "open time sheet",
            "view time sheet",
            "show my hours",
            "view my hours",
            "check timesheet",
            "check my hours",
            "show my time",
            "view my time",
            "show schedule"
        ),
        "show statistics" to listOf(
            "show statistics",
            "open statistics",
            "view statistics",
            "statistics page",
            "show stats",
            "open stats",
            "view stats",
            "stats page",
            "show my statistics",
            "show my stats",
            "statistics"
        ),
        "export csv" to listOf(
            "export csv",
            "export to csv",
            "save as csv",
            "download csv",
            "csv export",
            "export data csv",
            "save data csv",
            "download data csv",
            "export tasks csv",
            "save tasks csv",
            "export task csv",
            "save task csv"
        ),
        "export json" to listOf(
            "export json",
            "export to json",
            "save as json",
            "download json",
            "json export",
            "export data json",
            "save data json",
            "download data json",
            "export tasks json",
            "save tasks json",
            "export task json",
            "save task json"
        ),
        "export html" to listOf(
            "export html",
            "export to html",
            "save as html",
            "download html",
            "html export",
            "export data html",
            "save data html",
            "download data html",
            "export tasks html",
            "save tasks html",
            "export task html",
            "save task html"
        ),
        "export markdown" to listOf(
            "export markdown",
            "export to markdown",
            "save as markdown",
            "download markdown",
            "markdown export",
            "export data markdown",
            "save data markdown",
            "download data markdown",
            "export tasks markdown",
            "save tasks markdown",
            "export task markdown",
            "save task markdown",
            "export md",
            "export to md",
            "save as md",
            "export task md",
            "save task md"
        ),
        "export xml" to listOf(
            "export xml",
            "export to xml",
            "save as xml",
            "download xml",
            "xml export",
            "export data xml",
            "save data xml",
            "download data xml",
            "export tasks xml",
            "save tasks xml",
            "export task xml",
            "save task xml"
        ),
        "export text" to listOf(
            "export text",
            "export to text",
            "save as text",
            "download text",
            "text export",
            "export data text",
            "save data text",
            "download data text",
            "export tasks text",
            "save tasks text",
            "export task text",
            "save task text",
            "export plain text",
            "export to plain text",
            "save as plain text"
        )
    )
}
